import type { Course, Lesson, Question, Unit } from "./types";

const hint = (
  gentle: string,
  specific: string,
  partial: string,
): [string, string, string] => [gentle, specific, partial];

export const questionBank: Record<string, Question> = {
  "var-check-1": {
    id: "var-check-1",
    prompt: "In the expression 7 + n, which symbol is the variable?",
    kind: "text",
    answer: "n",
    skill: "Identify variables",
    hints: hint("Look for the value that can change.", "The number 7 is fixed.", "The letter represents the unknown value."),
    explanation: "n is the variable because its value is not fixed.",
    misconception: "constant-as-variable",
  },
  "var-check-2": {
    id: "var-check-2",
    prompt: "If m = 5, what is 3m + 2?",
    kind: "numeric",
    answer: "17",
    skill: "Evaluate expressions",
    hints: hint("Replace m with its value.", "Write 3 × 5 + 2.", "Multiply before adding: 15 + 2."),
    explanation: "Substitute 5 for m: 3(5) + 2 = 15 + 2 = 17.",
    misconception: "missed-substitution",
  },
  "var-check-3": {
    id: "var-check-3",
    prompt: "Which expression means “four more than a number x”?",
    kind: "choice",
    options: ["4x", "x + 4", "4 - x", "x ÷ 4"],
    answer: "x + 4",
    skill: "Translate phrases",
    hints: hint("“More than” signals addition.", "Begin with the unknown x.", "Add four to x."),
    explanation: "“Four more than x” means start with x and add 4, so x + 4.",
  },
  "var-practice-1": {
    id: "var-practice-1",
    prompt: "If a = 9, evaluate a − 3.",
    kind: "numeric",
    answer: "6",
    skill: "Evaluate expressions",
    hints: hint("Substitute 9 for a.", "The expression becomes 9 − 3.", "Subtract three from nine."),
    explanation: "a − 3 = 9 − 3 = 6.",
  },
  "var-practice-2": {
    id: "var-practice-2",
    prompt: "Write an expression for “a number y divided by 6.”",
    kind: "expression",
    answer: "y/6",
    skill: "Translate phrases",
    hints: hint("“Divided by” creates a fraction.", "The number y is the dividend.", "Place y over 6."),
    explanation: "The phrase translates to y ÷ 6, or y/6.",
  },
  "var-practice-3": {
    id: "var-practice-3",
    prompt: "If p = 4 and q = 3, evaluate 2p + q.",
    kind: "numeric",
    answer: "11",
    skill: "Evaluate expressions",
    hints: hint("Replace both letters.", "Write 2(4) + 3.", "Compute 8 + 3."),
    explanation: "2p + q = 2(4) + 3 = 8 + 3 = 11.",
  },
  "var-practice-4": {
    id: "var-practice-4",
    prompt: "Which quantities can vary in “cost c for t tickets”?",
    kind: "multi-select",
    options: ["c", "t", "the word tickets", "for"],
    answer: ["c", "t"],
    skill: "Identify variables",
    hints: hint("Choose symbols whose values may change.", "Words are labels, not quantities.", "Both c and t can represent changing numbers."),
    explanation: "c and t are variables: cost and ticket count can both change.",
  },
  "var-practice-5": {
    id: "var-practice-5",
    prompt: "A notebook costs d dollars. Write the cost of 5 notebooks.",
    kind: "expression",
    answer: "5*d",
    skill: "Model with variables",
    hints: hint("Five equal costs are combined.", "Use multiplication.", "Multiply 5 by d."),
    explanation: "Five notebooks at d dollars each cost 5d dollars.",
  },
  "var-mastery": {
    id: "var-mastery",
    prompt: "When k = 6, evaluate 4k − 5.",
    kind: "numeric",
    answer: "19",
    skill: "Evaluate expressions",
    hints: hint("Substitute first.", "Write 4(6) − 5.", "Compute 24 − 5."),
    explanation: "4(6) − 5 = 24 − 5 = 19.",
  },
  "expr-check-1": {
    id: "expr-check-1",
    prompt: "Simplify 3x + 5x.",
    kind: "expression",
    answer: "8*x",
    skill: "Combine like terms",
    hints: hint("The terms have the same variable part.", "Add the coefficients.", "3 + 5 = 8, and keep x."),
    explanation: "3x and 5x are like terms, so 3x + 5x = 8x.",
    misconception: "dropped-variable",
  },
  "expr-check-2": {
    id: "expr-check-2",
    prompt: "Simplify 7a + 2 − 3a + 5.",
    kind: "expression",
    answer: "4*a+7",
    skill: "Combine like terms",
    hints: hint("Group variable terms and constants.", "Combine 7a − 3a, then 2 + 5.", "The two groups become 4a and 7."),
    explanation: "7a − 3a = 4a and 2 + 5 = 7, so the result is 4a + 7.",
  },
  "expr-check-3": {
    id: "expr-check-3",
    prompt: "Use the distributive property to simplify 4(x + 3).",
    kind: "expression",
    answer: "4*x+12",
    skill: "Distributive property",
    hints: hint("Multiply every term inside the parentheses.", "Multiply 4 by x and by 3.", "4·x + 4·3."),
    explanation: "4(x + 3) = 4x + 12.",
    misconception: "partial-distribution",
  },
  "expr-practice-1": {
    id: "expr-practice-1",
    prompt: "Simplify 9y − 2y.",
    kind: "expression",
    answer: "7*y",
    skill: "Combine like terms",
    hints: hint("These are like terms.", "Subtract the coefficients.", "9 − 2 = 7."),
    explanation: "9y − 2y = (9 − 2)y = 7y.",
  },
  "expr-practice-2": {
    id: "expr-practice-2",
    prompt: "Simplify 5 + 2n + 6 + n.",
    kind: "expression",
    answer: "3*n+11",
    skill: "Combine like terms",
    hints: hint("Collect terms by type.", "Combine 2n + n and 5 + 6.", "Those groups are 3n and 11."),
    explanation: "2n + n = 3n and 5 + 6 = 11, giving 3n + 11.",
  },
  "expr-practice-3": {
    id: "expr-practice-3",
    prompt: "Simplify 3(2x − 5).",
    kind: "expression",
    answer: "6*x-15",
    skill: "Distributive property",
    hints: hint("Distribute 3 to both terms.", "Compute 3·2x and 3·(−5).", "The products are 6x and −15."),
    explanation: "3(2x − 5) = 6x − 15.",
  },
  "expr-practice-4": {
    id: "expr-practice-4",
    prompt: "Simplify 2p + 4q + 3p − q.",
    kind: "expression",
    answer: "5*p+3*q",
    skill: "Combine like terms",
    hints: hint("p-terms combine only with p-terms.", "Combine 2p + 3p and 4q − q.", "The groups become 5p and 3q."),
    explanation: "2p + 3p = 5p and 4q − q = 3q, so 5p + 3q.",
  },
  "expr-practice-5": {
    id: "expr-practice-5",
    prompt: "Which expression is equivalent to 6(x − 2) + x?",
    kind: "choice",
    options: ["7x − 12", "6x − 2", "7x − 2", "6x − 12"],
    answer: "7x − 12",
    skill: "Simplify expressions",
    hints: hint("Distribute before combining.", "6(x − 2) becomes 6x − 12.", "Combine 6x + x."),
    explanation: "6(x − 2) + x = 6x − 12 + x = 7x − 12.",
  },
  "expr-mastery": {
    id: "expr-mastery",
    prompt: "Simplify 5(2x + 1) − 3x.",
    kind: "expression",
    answer: "7*x+5",
    skill: "Simplify expressions",
    hints: hint("Begin with distribution.", "Write 10x + 5 − 3x.", "Combine 10x − 3x."),
    explanation: "5(2x + 1) − 3x = 10x + 5 − 3x = 7x + 5.",
  },
  "eq-check-1": {
    id: "eq-check-1",
    prompt: "Solve x + 8 = 15.",
    kind: "numeric",
    answer: "7",
    skill: "Addition equations",
    hints: hint("Undo the addition.", "Subtract 8 from both sides.", "x = 15 − 8."),
    explanation: "Subtracting 8 from both sides gives x = 7.",
  },
  "eq-check-2": {
    id: "eq-check-2",
    prompt: "Solve y − 6 = 10.",
    kind: "numeric",
    answer: "16",
    skill: "Subtraction equations",
    hints: hint("Use the inverse of subtracting 6.", "Add 6 to both sides.", "y = 10 + 6."),
    explanation: "Add 6 to both sides: y = 16.",
  },
  "eq-check-3": {
    id: "eq-check-3",
    prompt: "Solve 5m = 35.",
    kind: "numeric",
    answer: "7",
    skill: "Multiplication equations",
    hints: hint("Undo multiplication by 5.", "Divide both sides by 5.", "m = 35 ÷ 5."),
    explanation: "Divide both sides by 5 to get m = 7.",
  },
  "eq-practice-1": {
    id: "eq-practice-1",
    prompt: "Solve a + 12 = 20.",
    kind: "numeric",
    answer: "8",
    skill: "Addition equations",
    hints: hint("Isolate a.", "Subtract 12 from each side.", "a = 20 − 12."),
    explanation: "a = 8 because 8 + 12 = 20.",
  },
  "eq-practice-2": {
    id: "eq-practice-2",
    prompt: "Solve b − 9 = −2.",
    kind: "numeric",
    answer: "7",
    skill: "Subtraction equations",
    hints: hint("Undo subtracting 9.", "Add 9 to both sides.", "b = −2 + 9."),
    explanation: "Adding 9 to both sides gives b = 7.",
  },
  "eq-practice-3": {
    id: "eq-practice-3",
    prompt: "Solve 8c = 56.",
    kind: "numeric",
    answer: "7",
    skill: "Multiplication equations",
    hints: hint("Undo multiplying by 8.", "Divide both sides by 8.", "c = 56/8."),
    explanation: "56 ÷ 8 = 7, so c = 7.",
  },
  "eq-practice-4": {
    id: "eq-practice-4",
    prompt: "Solve d/4 = 6.",
    kind: "numeric",
    answer: "24",
    skill: "Division equations",
    hints: hint("Undo division by 4.", "Multiply both sides by 4.", "d = 6 × 4."),
    explanation: "Multiplying both sides by 4 gives d = 24.",
  },
  "eq-practice-5": {
    id: "eq-practice-5",
    prompt: "Put the solving steps for z − 11 = 4 in order.",
    kind: "ordering",
    options: ["Check: 15 − 11 = 4", "Add 11 to both sides", "Write z = 15"],
    answer: ["Add 11 to both sides", "Write z = 15", "Check: 15 − 11 = 4"],
    skill: "Equation reasoning",
    hints: hint("First undo the operation.", "Then state the solution.", "Checking comes after solving."),
    explanation: "Use the inverse operation, state z = 15, then verify it in the original equation.",
  },
  "eq-mastery": {
    id: "eq-mastery",
    prompt: "Solve −3x = 21.",
    kind: "numeric",
    answer: "-7",
    skill: "Multiplication equations",
    hints: hint("The coefficient is −3.", "Divide both sides by −3.", "x = 21 ÷ (−3)."),
    explanation: "Dividing both sides by −3 gives x = −7.",
  },
};

const deepLessons: Lesson[] = [
  {
    id: "understanding-variables",
    title: "Understanding Variables",
    objective: "Identify variables, translate phrases, and evaluate expressions by substitution.",
    duration: 18,
    status: "available",
    summary: "A variable is a symbol for a number that can change or is not yet known.",
    explanation: [
      "Mathematics uses variables to describe patterns and unknown quantities. In x + 4, x is the variable and 4 is a constant.",
      "A value can be substituted for a variable. If x = 3, then x + 4 becomes 3 + 4.",
      "An expression describes a quantity; an equation states that two expressions are equal.",
    ],
    keyIdea: "A variable is not an object or label—it represents a number.",
    commonMistake: "Writing 5 + x as 5x changes addition into multiplication. Operation words matter.",
    examples: [
      {
        title: "From words to symbols",
        prompt: "Write “seven less than a number n” as an expression.",
        steps: ["Start with the unknown number: n.", "“Seven less than” means subtract 7.", "The expression is n − 7."],
        takeaway: "The order in “less than” matters.",
      },
      {
        title: "Substitute and evaluate",
        prompt: "Evaluate 2a + 5 when a = 6.",
        steps: ["Replace a with 6: 2(6) + 5.", "Multiply first: 12 + 5.", "Add to get 17."],
        takeaway: "Use parentheses when substituting to preserve the expression.",
      },
    ],
    checks: ["var-check-1", "var-check-2", "var-check-3"],
    practice: ["var-practice-1", "var-practice-2", "var-practice-3", "var-practice-4", "var-practice-5"],
    mastery: ["var-mastery"],
    tutorContext: "Variables as changing or unknown numbers; substitution; translating simple phrases.",
  },
  {
    id: "simplifying-algebraic-expressions",
    title: "Simplifying Algebraic Expressions",
    objective: "Combine like terms and apply the distributive property accurately.",
    duration: 24,
    status: "available",
    summary: "Equivalent expressions may look different while producing the same value.",
    explanation: [
      "Like terms have exactly the same variable part. 3x and 8x are like terms; 3x and 3y are not.",
      "Combine like terms by adding or subtracting their coefficients while keeping the variable part unchanged.",
      "The distributive property multiplies the outside factor by every term inside parentheses.",
    ],
    keyIdea: "Coefficients combine; variable parts stay attached.",
    commonMistake: "In 3(x + 4), multiplying only x gives 3x + 4. The 3 must multiply both x and 4.",
    examples: [
      {
        title: "Collect like terms",
        prompt: "Simplify 6x + 4 − 2x + 9.",
        steps: ["Group like terms: (6x − 2x) + (4 + 9).", "Combine coefficients: 4x.", "Combine constants: 13. Result: 4x + 13."],
        takeaway: "Reordering terms is safe when their signs move with them.",
      },
      {
        title: "Distribute, then combine",
        prompt: "Simplify 2(3y − 4) + y.",
        steps: ["Distribute 2: 6y − 8 + y.", "Combine 6y and y.", "The result is 7y − 8."],
        takeaway: "Remove parentheses before combining outside terms.",
      },
    ],
    checks: ["expr-check-1", "expr-check-2", "expr-check-3"],
    practice: ["expr-practice-1", "expr-practice-2", "expr-practice-3", "expr-practice-4", "expr-practice-5"],
    mastery: ["expr-mastery"],
    tutorContext: "Terms, coefficients, constants, like terms, distributive property, and equivalence.",
  },
  {
    id: "solving-one-step-equations",
    title: "Solving One-Step Equations",
    objective: "Use inverse operations to isolate a variable and verify the result.",
    duration: 22,
    status: "available",
    summary: "Keep an equation balanced by performing the same valid operation on both sides.",
    explanation: [
      "An equation is balanced: both sides have the same value. To isolate the variable, undo its operation with an inverse operation.",
      "Addition and subtraction are inverses; multiplication and division are inverses.",
      "A solution should make the original equation true when substituted back in.",
    ],
    keyIdea: "Whatever you do to one side of an equation, do to the other side.",
    commonMistake: "Changing a sign without performing an operation on both sides is not a valid algebra step.",
    examples: [
      {
        title: "Undo addition",
        prompt: "Solve x + 14 = 23.",
        steps: ["Subtract 14 from both sides.", "x + 14 − 14 = 23 − 14.", "x = 9. Check: 9 + 14 = 23."],
        takeaway: "The check confirms the solution in the original equation.",
      },
      {
        title: "Undo division",
        prompt: "Solve p/5 = −3.",
        steps: ["Multiply both sides by 5.", "5(p/5) = 5(−3).", "p = −15. Check: −15/5 = −3."],
        takeaway: "A negative result is valid when it satisfies the equation.",
      },
    ],
    checks: ["eq-check-1", "eq-check-2", "eq-check-3"],
    practice: ["eq-practice-1", "eq-practice-2", "eq-practice-3", "eq-practice-4", "eq-practice-5"],
    mastery: ["eq-mastery"],
    tutorContext: "Equation balance, inverse operations, isolating a variable, and checking a solution.",
  },
];

const compactLesson = (id: string, title: string, objective: string, status: Lesson["status"] = "locked"): Lesson => ({
  id,
  title,
  objective,
  duration: 16,
  status,
  summary: objective,
});

export const algebraUnits: Unit[] = [
  {
    id: "numbers-variables",
    title: "Numbers and Variables",
    description: "Build the language of algebra from number properties to unknown quantities.",
    objectives: ["Classify numbers", "Use variables", "Translate verbal descriptions", "Evaluate expressions"],
    lessons: [
      deepLessons[0],
      compactLesson("number-systems", "The Number System", "Classify integers, rational numbers, and real numbers.", "available"),
      compactLesson("translating-phrases", "Translating Words into Algebra", "Represent everyday quantities with expressions.", "available"),
      compactLesson("evaluating-expressions", "Evaluating Expressions", "Substitute values while respecting order of operations.", "review"),
    ],
    quizQuestionIds: ["var-check-2", "var-practice-2", "var-mastery"],
  },
  {
    id: "expressions",
    title: "Expressions",
    description: "Read, build, and simplify algebraic expressions.",
    objectives: ["Recognize terms", "Combine like terms", "Distribute factors", "Compare equivalent expressions"],
    lessons: [
      compactLesson("terms-and-coefficients", "Terms, Factors, and Coefficients", "Describe the parts of an expression.", "complete"),
      deepLessons[1],
      compactLesson("order-of-operations", "Order of Operations", "Evaluate expressions with grouping and exponents.", "available"),
      compactLesson("equivalent-expressions", "Equivalent Expressions", "Determine whether two expressions are equivalent.", "available"),
    ],
    quizQuestionIds: ["expr-check-2", "expr-practice-3", "expr-mastery"],
  },
  {
    id: "one-step-equations",
    title: "One-Step Equations",
    description: "Solve equations by maintaining balance and using inverse operations.",
    objectives: ["Model equality", "Use inverse operations", "Solve four equation types", "Check solutions"],
    lessons: [
      compactLesson("balance-model", "The Balance Model", "Explain equality as balance.", "complete"),
      deepLessons[2],
      compactLesson("negative-equations", "Equations with Negative Numbers", "Reason accurately about negative coefficients.", "available"),
      compactLesson("equation-word-problems", "One-Step Word Problems", "Build and solve equations from situations.", "available"),
    ],
    quizQuestionIds: ["eq-check-1", "eq-practice-4", "eq-mastery"],
  },
  {
    id: "multi-step-equations",
    title: "Multi-Step Equations",
    description: "Plan and carry out several valid steps to isolate a variable.",
    objectives: ["Simplify before solving", "Solve variables on both sides", "Clear fractions"],
    lessons: [
      compactLesson("two-step-equations", "Two-Step Equations", "Reverse operations in a sensible order.", "available"),
      compactLesson("variables-both-sides", "Variables on Both Sides", "Collect variable terms before solving."),
      compactLesson("fraction-equations", "Equations with Fractions", "Clear denominators safely."),
    ],
    quizQuestionIds: ["eq-check-3", "expr-check-3", "eq-mastery"],
  },
  {
    id: "inequalities",
    title: "Inequalities",
    description: "Describe and solve ranges of possible values.",
    objectives: ["Read inequality symbols", "Graph solutions", "Reverse signs when required"],
    lessons: [
      compactLesson("comparing-values", "Comparing Values", "Interpret inequality symbols.", "available"),
      compactLesson("solving-inequalities", "Solving Inequalities", "Apply inverse operations to inequalities."),
      compactLesson("graphing-inequalities", "Graphing on a Number Line", "Show open and closed endpoints."),
      compactLesson("compound-inequalities", "Compound Inequalities", "Represent intersections and unions."),
    ],
    quizQuestionIds: ["eq-check-1", "eq-practice-2", "eq-mastery"],
  },
  {
    id: "coordinate-plane",
    title: "Coordinate Plane",
    description: "Locate, compare, and measure points on the coordinate plane.",
    objectives: ["Plot ordered pairs", "Name quadrants", "Measure horizontal and vertical distance"],
    lessons: [
      compactLesson("ordered-pairs", "Ordered Pairs", "Read x- and y-coordinates.", "available"),
      compactLesson("quadrants", "Quadrants and Axes", "Locate points by sign."),
      compactLesson("coordinate-distance", "Distance on the Plane", "Measure axis-aligned distances."),
    ],
    quizQuestionIds: ["var-check-2", "expr-check-1", "eq-check-3"],
  },
  {
    id: "linear-relationships",
    title: "Linear Relationships",
    description: "Connect constant rate of change, tables, graphs, and equations.",
    objectives: ["Find rate of change", "Interpret slope", "Write linear equations", "Graph lines"],
    lessons: [
      compactLesson("patterns-and-rates", "Patterns and Rates", "Recognize constant change.", "available"),
      compactLesson("slope", "Understanding Slope", "Calculate rise over run."),
      compactLesson("linear-equations", "Writing Linear Equations", "Use y = mx + b."),
      compactLesson("graphing-lines", "Graphing Linear Relationships", "Connect equations and graphs."),
    ],
    quizQuestionIds: ["var-practice-3", "expr-mastery", "eq-mastery"],
  },
];

export const algebraCourse: Course = {
  id: "algebra-foundations",
  title: "Algebra Foundations",
  level: "Foundation · Grades 6–9",
  description: "A careful path from variables and expressions to equations, inequalities, and linear relationships.",
  duration: "8–10 weeks",
  unitCount: algebraUnits.length,
  prerequisites: ["Whole-number operations", "Basic fractions and decimals"],
  skills: ["Variables", "Expressions", "Equations", "Inequalities", "Coordinate plane", "Linear relationships"],
  progress: 38,
  featured: true,
};

export const courses: Course[] = [
  algebraCourse,
  {
    id: "arithmetic-foundations",
    title: "Arithmetic Foundations",
    level: "Foundation",
    description: "Build fluency with whole numbers, fractions, decimals, ratios, and percent.",
    duration: "10 weeks",
    unitCount: 8,
    prerequisites: ["None"],
    skills: ["Number sense", "Fractions", "Ratios"],
    progress: 72,
    featured: true,
  },
  {
    id: "geometry",
    title: "Geometry",
    level: "Intermediate",
    description: "Reason about shapes, transformations, measurement, similarity, and proof.",
    duration: "12 weeks",
    unitCount: 9,
    prerequisites: ["Algebra Foundations"],
    skills: ["Proof", "Similarity", "Measurement"],
    featured: true,
  },
  {
    id: "algebra-ii",
    title: "Algebra II",
    level: "Advanced secondary",
    description: "Study functions, polynomials, exponentials, logarithms, and complex numbers.",
    duration: "14 weeks",
    unitCount: 10,
    prerequisites: ["Algebra I"],
    skills: ["Functions", "Polynomials", "Logarithms"],
  },
  {
    id: "trigonometry",
    title: "Trigonometry",
    level: "Advanced secondary",
    description: "Connect angles, circles, triangles, graphs, and periodic change.",
    duration: "8 weeks",
    unitCount: 7,
    prerequisites: ["Geometry", "Algebra II"],
    skills: ["Unit circle", "Identities", "Modeling"],
  },
  {
    id: "precalculus",
    title: "Precalculus",
    level: "Advanced secondary",
    description: "Unify function behavior and mathematical modeling before calculus.",
    duration: "12 weeks",
    unitCount: 9,
    prerequisites: ["Algebra II", "Trigonometry"],
    skills: ["Functions", "Sequences", "Limits"],
  },
  {
    id: "calculus-foundations",
    title: "Calculus Foundations",
    level: "University preparation",
    description: "Develop intuition for limits, derivatives, integrals, and change.",
    duration: "14 weeks",
    unitCount: 10,
    prerequisites: ["Precalculus"],
    skills: ["Limits", "Derivatives", "Integrals"],
  },
  {
    id: "statistics-probability",
    title: "Statistics & Probability",
    level: "Intermediate",
    description: "Learn to reason from data, quantify uncertainty, and evaluate evidence.",
    duration: "10 weeks",
    unitCount: 8,
    prerequisites: ["Arithmetic Foundations"],
    skills: ["Data", "Probability", "Inference"],
  },
  {
    id: "mathematical-reasoning",
    title: "Mathematical Reasoning",
    level: "All levels",
    description: "Strengthen logic, representation, problem-solving, and proof habits.",
    duration: "6 weeks",
    unitCount: 6,
    prerequisites: ["Curiosity"],
    skills: ["Logic", "Strategy", "Communication"],
  },
  {
    id: "university-pathways",
    title: "University Mathematics Pathways",
    level: "University",
    description: "A curated continuation inspired by the original School of Math curriculum: analysis, linear algebra, differential equations, statistics, computing, and research.",
    duration: "Self-paced",
    unitCount: 12,
    prerequisites: ["Precalculus"],
    skills: ["Analysis", "Algebra", "Statistics", "Computing"],
  },
];

export function getLesson(id: string): Lesson | undefined {
  return algebraUnits.flatMap((unit) => unit.lessons).find((lesson) => lesson.id === id);
}

export function getQuestion(id: string): Question {
  const question = questionBank[id];
  if (!question) throw new Error(`Unknown question: ${id}`);
  return question;
}

